name: blobby
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  provider: ^6.1.2
  #animations: ^2.0.11
  flutter_animate: ^4.5.0

  
  #ui customizations
  cached_network_image: ^3.4.1
  google_fonts: ^6.0.0
  flutter_svg: ^2.0.7

  flutter_spinkit: ^5.2.1
  loading_animation_widget: ^1.2.0+4
  fluttertoast: ^8.2.12

  #for network calls, network connection checks & jwt decoder
  internet_connection_checker: ^1.0.0+1
  http: ^1.3.0
  
  #screen util (enhances mobile responsiveness)
  flutter_screenutil: ^5.9.0



dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/